default['mysql-install']['version'] = "5.6"
default['mysql-install']['bind_address'] = "127.0.0.1"
default['mysql-install']['port'] = "3306"
default['mysql-install']['password'] = "root"
default['mysql-install']['dbname'] = "magento"